# Generated by Django 3.2.6 on 2021-08-17 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('lancamento', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 58, 3, 465878, tzinfo=utc))),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gender', models.CharField(choices=[('A', 'Multiplayer'), ('B', 'Single-Player'), ('C', 'MMO')], default='A', max_length=10)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/')),
                ('produtora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.produtora')),
            ],
        ),
    ]
