# Generated by Django 3.2.6 on 2021-08-17 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210817_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtora',
            old_name='description',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 33, 58, 290475, tzinfo=utc)),
        ),
    ]
