# Generated by Django 3.2.6 on 2021-08-17 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210817_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtora',
            old_name='descricao',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 45, 15, 339174, tzinfo=utc)),
        ),
    ]
