# Generated by Django 3.2.4 on 2021-08-31 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210817_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 12, 41, 34, 291879, tzinfo=utc)),
        ),
    ]
