# Generated by Django 3.2.4 on 2021-08-31 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_games_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 13, 45, 39, 556071, tzinfo=utc)),
        ),
    ]
