# Generated by Django 3.2.4 on 2021-09-08 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_games_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 14, 22, 22, 47551, tzinfo=utc)),
        ),
    ]
