# Generated by Django 3.2.5 on 2021-10-03 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210908_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtora',
            name='logo',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 1, 26, 40, 492547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='produtora',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
