# Generated by Django 3.2.4 on 2021-10-19 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_games_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 11, 48, 24, 999733, tzinfo=utc)),
        ),
    ]
