# Generated by Django 4.2.4 on 2023-08-22 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_games_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='gender',
            field=models.CharField(choices=[('A', 'Multiplayer'), ('B', 'Single-Player'), ('C', 'MMO'), ('D', 'Co-Op'), ('E', 'Battle Royale')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 15, 59, 846791, tzinfo=datetime.timezone.utc)),
        ),
    ]
