# Generated by Django 4.2.4 on 2023-08-22 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_games_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='lancamento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 24, 41, 566753, tzinfo=datetime.timezone.utc)),
        ),
    ]
